version: '3.5'

services:
  netbeans:
    build: .
    environment:
      - DISPLAY=$DISPLAY

    volumes:
      - ./nbProjects:/root/NetBeansProjects
      - "${HOME}/.Xauthority:/root/.Xauthority:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix
    dns_search: .  
    network_mode: "host"